name = "MRFingerprintingRecon"
uuid = "f4798e02-a7e0-47f5-a571-12dd775704d3"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>"]
version = "0.3.6"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
RegularizedLeastSquares = "1e9c538a-f78c-5de5-8ffb-0b6dbe892d23"

[compat]
FFTW = "1"
LinearOperators = "2"
MRIReco = "0.4,0.5"
NFFT = "0.12.1, 0.13"
NFFTTools = "0.2"
Polyester = "0.6"
RegularizedLeastSquares = "0.8"
julia = "1.6"
