name = "MRISubspaceRecon"
uuid = "81225dec-f002-11f0-8080-35af0c2c6e2d"
version = "0.9.1-DEV"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>"]

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
MRICoilSensitivities = "c57eb701-aafc-44a2-a53c-128049758959"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
IterativeSolvers = "0.9"
CUDA = "5.8.3"
ExponentialUtilities = "1"
MRICoilSensitivities = "0.1.1"
julia = "1.11"
LinearAlgebra = "1.7"
NonuniformFFTs = "0.9"
OhMyThreads = "0.8.3"
LinearOperators = "2.11"
FFTW = "1"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
MRISubspaceReconCUDAExt = "CUDA"
