name = "MRFingerprintingRecon"
uuid = "f4798e02-a7e0-47f5-a571-12dd775704d3"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>"]
version = "0.8.0"

[deps]
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MRICoilSensitivities = "c57eb701-aafc-44a2-a53c-128049758959"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
ExponentialUtilities = "1"
FFTW = "1.5"
LinearAlgebra = "1.7"
LinearOperators = "2"
MRICoilSensitivities = "0.1.1"
NFFT = "0.12.1, 0.13"
NFFTTools = "0.2"
Polyester = "0.6, 0.7"
julia = "1.7"
