name = "MRFingerprintingRecon"
uuid = "f4798e02-a7e0-47f5-a571-12dd775704d3"
version = "0.8.7-DEV"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>"]

[deps]
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MRICoilSensitivities = "c57eb701-aafc-44a2-a53c-128049758959"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
ExponentialUtilities = "1"
FFTW = "1.5"
IterativeSolvers = "0.9"
LinearAlgebra = "1.7"
LinearOperators = "2"
MRICoilSensitivities = "0.1.1"
NonuniformFFTs = "0.8, 0.9"
OhMyThreads = "0.8.3"
Polyester = "0.6, 0.7"
julia = "1.10"
